config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :colocations do

    resources :user_colocations, only: [:new, :create]
    resources :lists, except: [:home] do
      resources :items
    end
    resources :notes, except: [:home]
    resources :chatrooms, only: [:show] do
      resources :messages, only: :create
    end
    resources :events, except: [:home]
    get "contacts", to: "pages#contacts", as: :contacts
  end
  get "deletephoto", to: "colocations#deletephoto", as: :deletephoto
  get "calendar", to: "pages#calendar", as: :calendar
  get "profile", to: "dashboards#profile", as: :profile

  patch "update_profile_infos", to: "dashboards#update_profile_infos"

end
# sortir edit et update des routes param de coloc

app/models/list.rb
class List < ApplicationRecord
  belongs_to :colocation
  has_many :items, dependent: :destroy
  validates :title, presence: true, length: { minimum: 2 }

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
   @lists = List.where(colocation_id: params[:colocation_id])
   @colocation = Colocation.find(params[:colocation_id])
  # @items = Item.where(list_id: params[:id])
  #  =@items = Item.where(colocation: @colocation.lists)
   @item = Item.new
   @list_new = List.new
  end

  def show
    # @list = List.find(params[:id])
    # @items = Item.where(list_id: params[:id])
    # @colocation = Colocation.find(params[:colocation_id])
  end

  def new
    @colocation = Colocation.find(params[:colocation_id])
    @list = List.new

  end

  def create
    @colocation = Colocation.find(params[:colocation_id])
    @list = List.new(list_params)
    @list.colocation = @colocation
    if @list.save
      redirect_to colocation_lists_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @colocation = Colocation.find(params[:colocation_id])
    @list = List.find(params[:id])
  end

  def update
    @colocation = Colocation.find(params[:colocation_id])
    @list = List.find(params[:id])
    @list.update(list_params)
    if @list.save
      redirect_to colocation_list_path(@colocation, @list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @colocation = Colocation.find(params[:colocation_id])
    @list = List.find(params[:id])
    @list.destroy

    redirect_to colocation_lists_path
  end

    private

  def list_params
    params.require(:list).permit(:title, :colocation_id)
  end
end

app/views/lists/edit.html.erb
<h1>Edit your list</h1>
<div class="container">
<%= simple_form_for [@colocation, @list], method: :patch do |f| %>
  <%= f.input :title %>
  <%= f.submit %>
<% end %>
</div>

app/views/lists/index.html.erb
<div class="indexlist">
  <div class="container">
  <h1>Nos listes partagées</h1>

    <div class="accordion" id="accordionPanel">
        <div class="showlist mt-5">
          <% @lists.each do |list| %>

            <%# ===================== bouton deroulant les items ======================= %>
            <div class="list-index" id="heading<%=list.id %>">

            <%# ici ok %>


              <%= link_to colocation_list_path(@colocation, list), data: {turbo_method: :delete, turbo_confirm: "Etes-vous sûr.e ?"} do %>
                <i class="fa-solid fa-circle-xmark deletelist"></i>
              <% end %>
              <h5 class="mb-0 mt-2">
                <button class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#collapse<%=list.id%>" aria-expanded="false" aria-controls="collapse<%=list.id%> ">
                <%=list.title.upcase %>
                </button>
              </h5>
            </div>

            <%# ===================== elements qui se deroulent ======================= %>

            <div id="collapse<%=list.id%>" class="collapse" aria-labelledby="heading<%=list.id %>" data-bs-parent="#accordion">
              <div class="px-5">
                <div class="list-item">
                  <div class="d-flex justify-content-between" data-bs-toggle="modal" data-bs-target="#exampleModal-<%=list.id %>">
                    <div class="add-item">
                      <i class="fa-solid fa-plus"></i>
                    </div>
                    <div class="add-item mb-3">
                    Ajouter un nouvel élément
                    </div>
                  </div>
                </div>

              <%# ===================== liste d'items ======================= %>
                <%= render list.items.order(:created_at), colocation: @colocation, list: list %>
              </div>
            </div>

            <div class="modal fade <%=list.id %>" id="exampleModal-<%=list.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">



              <div class="modal-dialog">
                <div class="modal-content">

                  <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Ajouter un élément</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <%= simple_form_for [@colocation, list, @item] do |f| %>
                      <%= f.input :name, label: "Nom" %>
                      <%= f.input :description %>
                      <%= f.button :submit, 'Enregistrer', class: "btn-pillpink" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <%# ---- Fin Modal %>
          <% end %>
      </div>
    </div>




    <div class="outside-btn">
        <div class="add-button ">
          <i class="fa-solid fa-circle-plus button-add-yellow" data-bs-toggle="modal" data-bs-target="#newListModal"></i>
        </div>
      </div>
  </div>
</div>

              <%# Modal modification liste %>
       <div class="modal fade" id="newListModal" tabindex="-1" aria-labelledby="newListModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title fs-5" id="newListModalLabel">Créer une liste</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <%= simple_form_for [@colocation, @list_new] do |f| %>
                      <%= f.input :title, label: "Titre" %>
                      <%= f.button :submit, "Créer ma liste", class: "btn-pillpink" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>

app/views/lists/new.html.erb
<div class="new-list">
  <div class="container">
    <h1>Nouvelle liste</h1>
    <%= link_to colocation_lists_path do %>
        <i class="fa-solid fa-arrow-left button-add-yellow ms-5"></i>
      <% end %>
      <%= simple_form_for [@colocation, @list] do |f| %>
        <%= f.input :title, label: "Titre" %>
        <%= f.button :submit, "Créer ma liste", class: "btn btn-light " %>
      <% end %>
        <br>
        <br>
        <br>
  </div>
</div>

app/views/lists/show.html.erb
<div class="showlist container">
  <div class="title d-flex justify-content-center mt-5 mb-5">
    <h1> <%= @list.title %> </h1>
    <i data-bs-toggle="modal" class="fa-regular fa-pen-to-square edit-button" data-bs-target="#editList"></i>
  </div>
  <% if @items.count == 0 %>
    <p>Ajoutez votre premier élément</p>
  <% else %>
  <div class="px-5">
    <%= render @items %>
  </div>
  <% end %>

  <%= link_to new_colocation_list_item_path(@colocation, @list) do%>
  <i class="fa-solid fa-circle-plus button-add-yellow"></i>
  <% end %><br>
  <%= link_to colocation_lists_path do %>
  <i class="fa-solid fa-arrow-left button-add-yellow"></i>
  <% end %>

</div>


<!-- Modal -->
<div class="modal fade" id="editList" tabindex="-1" aria-labelledby="editList" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">
          <div class="container">
            <%= simple_form_for [@colocation, @list], method: :patch do |f| %>
            <%= f.input :title %>
            <%= f.button :submit, 'Enregistrer', class: "btn-pillpink" %>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>