config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :colocations do

    resources :user_colocations, only: [:new, :create]
    resources :lists, except: [:home] do
      resources :items
    end
    resources :notes, except: [:home]
    resources :chatrooms, only: [:show] do
      resources :messages, only: :create
    end
    resources :events, except: [:home]
    get "contacts", to: "pages#contacts", as: :contacts
  end
  get "deletephoto", to: "colocations#deletephoto", as: :deletephoto
  get "calendar", to: "pages#calendar", as: :calendar
  get "profile", to: "dashboards#profile", as: :profile

  patch "update_profile_infos", to: "dashboards#update_profile_infos"

end
# sortir edit et update des routes param de coloc

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :colocation
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def show
    @note = Note.find(params[:id])
  end

  def index
    @colocation = Colocation.find(params[:colocation_id])
    @notes = Note.where(colocation_id: params[:colocation_id])
    @note = Note.new
  end

  def new
    @colocation = Colocation.find(params[:colocation_id])
    @note = Note.new
  end

  def create
    @colocation = Colocation.find(params[:colocation_id])
    @note = Note.new(note_params)
    @note.colocation = @colocation
    # if @note.save
    #   redirect_to colocation_notes_path
    # else
    #   render :new, status: :unprocessable_entity
    # end


    @note.save
    respond_to do |format|
      format.html { redirect_to colocation_notes_path }
      format.text { render partial: "notes/note", locals: {note: @note}, formats: [:html] }
    end
  end

  def edit
    @colocation = Colocation.find(params[:colocation_id])
    @note = Note.find(params[:id])

  end

  def update
    # @colocation = Colocation.find(params[:colocation_id])
    @note = Note.find(params[:id])
    @note.update(note_params)
    if @note.save
      redirect_to colocation_notes_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @colocation = Colocation.find(params[:colocation_id])
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to colocation_notes_path
  end
  # Never trust parameters from the scary internet, only allow the white list through.

  def note_params
    params.require(:note).permit(:title, :content)
  end
end

app/views/notes/_form.html.erb
<div class="container d-none " data-notes-target="form" style="margin-bottom: 200px;">
    <h2 class="text-center">Creer votre note</h1>

      <%= simple_form_for [@colocation, @note], action: "submit->notes#send" do |f| %>

      <%= f.input :title, :label => "Titre de la note"  %>
      <%= f.input :content, :label => "Contenu de la note" %>
      <%= f.button :submit, "Ajouter la note", class: "btn btn-primary " %>
      <a href="" class="btn btn-danger" data-notes-target="annuler" data-action="click->notes#annuler">Annuler</a>
      <%= link_to "Annuler", colocation_notes_path, class: "btn btn-danger" %>
      <% end %>

  </div>

app/views/notes/_note.html.erb
  <div class="card-purple even-<%= note.id%3 %>" data-notes-target="card">
      <h2><%= note.title %> <div class="menu-nav">
        <div class="menu-item"></div>
        <div class="dropdown-container" tabindex="-1">
          <div class="three-dots"></div>
          <div class="dropdown">
            <%= link_to edit_colocation_note_path(@colocation, note) do  %><div>Modifier</div> <% end %>
            <%= link_to [@colocation, note], data: { 'turbo-method': :delete, 'turbo-confirm': 'Etes vous sur.e?' } do  %><div>Supprimer</div> <% end %>

          </div>
        </div>
      </div></h2>






      <p><%= note.content %></p>
      <%# <%= link_to "Modifier cet note", edit_colocation_note_path(@colocation, note), class: "btn btn-primary" %>



  </div>

app/views/notes/edit.html.erb
<div class="container mb-5 w-50 bg-test p-3 rounded-5 mt-5 ">
<h1>Editez votre note</h1>
  <%= simple_form_for [@colocation, @note] do |f| %>
  <%= f.error_notification %>

  <%= f.input :title, :label => "Titre de la note"  %>

  <%= f.input :content, :label => "Description de la note" %>



  <%= f.button :submit, "Mise à jour de la note", class: "btn-create" %>
  <%= f.button :submit, "Annuler", class: "btn-cancel" %>
  <% end %>
  <%= link_to "retournez sur les notes", colocation_notes_path %>
</div>

app/views/notes/index.html.erb
<div class="container text-center" data-controller="notes">
  <h1 class="head-title">NOTES IMPORTANTES</h1>
  <div class="parent" id="notes">
    <% @notes.each do |note| %>
    <%= render "note", note: note %>
    <% end %>
  </div>

  <div class="container d-none mt-5 border border-warning rounded-5 shadow p-3" data-notes-target="display" style="margin-bottom: 200px;">
    <h2 class="text-center">Creer votre note</h1>

      <%= simple_form_for [@colocation, @note], html: {

    data: {
      notes_target: "form",
      action: "submit->notes#send"
    } } do |f| %>

      <%= f.input :title, :label => "Titre"  %>
      <%= f.input :content, :label => "Contenu" %>
      <%= f.button :submit, "Ajouter la note", class: "btn btn-success "    %>
      <a href="" class="btn " style=" background-color: rgba(206, 119, 119, 0.9)" data-notes-target="annuler" data-action="click->notes#annuler">Annuler</a>
      <%# <%= link_to "Annuler", colocation_notes_path, class: "btn btn-danger" %>
      <% end %>

  </div>
  <div><a>
      <i class="fa-solid fa-circle-plus button-add-yellow" data-notes-target="button"
        data-action="click->notes#addNotes" style="margin-top: 32px;"></i>
    </a>
    <p class="d-none" style="margin-bottom: 100px;" data-notes-target="error">Vous ne pouvez plus ajouter de notes, max:
      10notes</p>
  </div>


</div>

app/views/notes/new.html.erb
<div class="container mb-5 w-50 bg-test p-3 mt-5  ">
<h1 class="text-center">Creer votre note</h1>

<%= simple_form_for [@colocation, @note] do |f| %>


  <%= f.input :title, :label => "Titre de la note"  %>

  <%= f.input :content, :label => "Contenu de la note" %>





  <%= f.button :submit, "Ajouter la note", class: "btn btn-primary " %>

  <%= link_to "retour aux notes", colocation_notes_path, class: "btn btn-danger" %>
  <% end %>

</div>