config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :colocations do

    resources :user_colocations, only: [:new, :create]
    resources :lists, except: [:home] do
      resources :items
    end
    resources :notes, except: [:home]
    resources :chatrooms, only: [:show] do
      resources :messages, only: :create
    end
    resources :events, except: [:home]
    get "contacts", to: "pages#contacts", as: :contacts
  end
  get "deletephoto", to: "colocations#deletephoto", as: :deletephoto
  get "calendar", to: "pages#calendar", as: :calendar
  get "profile", to: "dashboards#profile", as: :profile

  patch "update_profile_infos", to: "dashboards#update_profile_infos"

end
# sortir edit et update des routes param de coloc

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <% if current_user %>
      <% colocation = Colocation.find(current_user.user_colocations.first.colocation.id)  %>
      <%= link_to colocation_path(colocation.id), class: "navbar-brand" do %>
        <%= image_tag('logo.png.png') %>
      <% end %>
    <% end %>

        <% if user_signed_in? %>
          <h1 class="coloc-name"><%= current_user.colocations.first.name %></h1>
          <li class="nav-item dropdown">
            <% if current_user.photo.key %>
                <%= cl_image_tag current_user.photo.key, width: 32, height: 32, crop: :thumb, gravity: :face, class: "profile-avatar", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
                <%= image_tag("avatar.png.png", width: 32, height: 32, crop: :thumb, gravity: :face, class: "profile-avatar", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false ) %>
            <% end %>

              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to profile_path(@user), class: "dropdown-item" do %> <i class="fa-regular fa-address-card"></i> Mon profil <% end %>
                <%= link_to colocation_contacts_path(current_user.user_colocations.first.colocation_id), class: "dropdown-item" do %> <i class="fa-solid fa-phone"></i> Nos contacts <% end %>
                <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" do %> <i class="fa-solid fa-right-from-bracket"></i> Se déconnecter <% end %>
              </div>
            </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>

  </div>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<% if current_user %>



<nav class="navbar navbar-expand-lg navbar-light navbarbotom">
<% colocation = Colocation.find(current_user.user_colocations.first.colocation.id)  %>
  <%= link_to colocation_path(colocation.id) do  %>
    <i class="fas fa-house <%= active_class(colocation_path(colocation.id)) %>"></i>
  <% end %>
  <%= link_to colocation_lists_path(current_user.user_colocations.first.colocation_id) do  %>
    <i class="fas fa-list <%= active_class(colocation_lists_path(current_user.user_colocations.first.colocation_id)) %>"></i>
  <% end %>
  <%= link_to calendar_path do  %>
    <i class="fas fa-calendar-week <%= active_class(calendar_path) %>"></i>
  <% end %>

  <%= link_to colocation_notes_path(current_user.user_colocations.first.colocation_id) do  %>
    <i class="far fa-sticky-note <%= active_class(colocation_notes_path(current_user.user_colocations.first.colocation_id)) %>"></i>
  <% end %>

  <% if user_signed_in? %>
    <%# <li class="nav-item active" data-controller="notification-subscription" data-notification-subscription-target="notif" data-notification-subscription-user-id-value="<%=current_user.id%>
      <%#<%= current_user.unread_messages %>
      <%# </li>  %>
  <%# je choisis ci-dessous la colocation du current_user -> a modifier si le current_user a plusieurs colocations %>
     <% colocation = Colocation.find(current_user.user_colocations.first.colocation.id)  %>
    <% chatroom = Chatroom.find_by(colocation: colocation)  %>
    <%# if current_user && chatroom %>
      <%= link_to colocation_chatroom_path(colocation.id, chatroom.id), class: "navbar-brand" do  %>
          <i class="fas fa-comment-dots relat <%= active_class(colocation_chatroom_path(colocation.id, chatroom.id)) %>"></i>
            <span class="badge" data-controller="notification-subscription" data-notification-subscription-target="notif" data-notification-subscription-user-id-value="<%=current_user.id%>"><%= current_user.unread_messages %></span>
      <% end %>
  <% end %>
</nav>
<% end %>





<%#= current_user.unread_messages == 0 ? 'd-none' : '' %>
<%#= current_user.unread_messages == 0 ? 'd-none' : '' %>

app/views/shared/_notification.html.erb
<span class="badge" data-controller="notification-subscription" data-notification-subscription-target="notif" data-notification-subscription-user-id-value="<%=user.id%>"><%= user.unread_messages %></span>