config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :colocations do

    resources :user_colocations, only: [:new, :create]
    resources :lists, except: [:home] do
      resources :items
    end
    resources :notes, except: [:home]
    resources :chatrooms, only: [:show] do
      resources :messages, only: :create
    end
    resources :events, except: [:home]
    get "contacts", to: "pages#contacts", as: :contacts
  end
  get "deletephoto", to: "colocations#deletephoto", as: :deletephoto
  get "calendar", to: "pages#calendar", as: :calendar
  get "profile", to: "dashboards#profile", as: :profile

  patch "update_profile_infos", to: "dashboards#update_profile_infos"

end
# sortir edit et update des routes param de coloc

app/models/colocation.rb
class Colocation < ApplicationRecord
  validates :name, presence: true, length: { minimum: 2 }
  has_many :notes, dependent: :destroy
  has_many :lists, dependent: :destroy
  has_many :items, through: :lists
  # has_many :user_colocations
  has_many :user_colocations
  has_one :chatroom, dependent: :destroy
  has_many :users, through: :user_colocations
  has_many :events, dependent: :destroy
  has_one_attached :photo
end

app/controllers/colocations_controller.rb
class ColocationsController < ApplicationController
  def show
    @colocation = Colocation.find(params[:id])
    @user_colocation = UserColocation.new
    # if params[:new_roomate]
    #   new_roomate = User.find_by(email: params[:new_roomate])
    #   if new_roomate
    #     UserColocation.create(colocation_id: @colocation.id, user_id: new_roomate.id)
    #   else

    #   end
    # end
  end

  def index
  end

  def new
    # @user_colocations = UserColocation.new
    @colocation = Colocation.new
  end

  def create
    @colocation = Colocation.new(colocation_params)
    if @colocation.save
      @chatroom = Chatroom.create(colocation_id: @colocation.id)
      redirect_to colocation_path(@colocation)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @colocation = Colocation.find(params[:id])
  end

  def update
    @colocation = Colocation.find(params[:id])
    if @colocation.update(colocation_params)
      redirect_to colocation_path(@colocation)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def deletephoto
    @colocation = Colocation.find(params[:format])
    @colocation.photo.purge
    redirect_to colocation_path(@colocation)
  end
  # Never trust parameters from the scary internet, only allow the white list through.


    private

  def colocation_params
    params.require(:colocation).permit(:name, :photo)
  end
end

app/views/colocations/new.html.erb
<div class="container mb-5 w-50 bg-test p-3 mt-5  ">
<h1 class="text-center">Créer votre coloc</h1>
  <%= simple_form_for @colocation do |f| %>
  <%= f.error_notification %>

  <%= f.input :name, :label => "nom de la colocation"  %>

  <%= f.button :submit, "Création Colocation", class: "btn-create " %>
  <%= f.button :submit, "Annuler", class: "btn-cancel " %>
  <% end %>
</div>

app/views/colocations/show.html.erb
<div class="colocation-show">
  <div class="container">

  <h2> Bienvenue chez nous <i class="fa-solid fa-heart"></i></h2>

    <div class="coloc-photo mt-5">
      <% if @colocation.photo.key %>
        <%= cl_image_tag @colocation.photo.key, class: "photocoloc" %>
        <%= link_to deletephoto_path(@colocation) do %>
          <i class="fa-solid fa-circle-xmark deletephoto"></i>
        <% end %>
      <% else %>
        <button type="button" class="addphotocoloc" data-bs-toggle="modal" data-bs-target="#exampleModal">
        <i class="fa-solid fa-plus"></i>
        Ajouter notre photo de groupe
        </button>
      <% end %>
    </div>

    <div class="colocataires">
      <% @colocation.users.each do |user| %>
            <div class="colocataire">
                <%= user.nickname %> <br>
              <% if user.photo.key %>
                <%= cl_image_tag user.photo.key, width: 40, height: 40, crop: :thumb, gravity: :face, class: "profile-avatar" %>
              <% else %>
                <%= image_tag("avatar.png.png", height: '32', width: '32') %>
              <% end %>
            </div>
      <% end %>
    </div>

    <div class="newroomate">
      <strong><i class="fa-solid fa-user-plus"></i> Ajouter un colocataire :</strong>
      <br>
      <br>

      <%= simple_form_for [@colocation, @user_colocation] do |f| %>
      <%= f.input :user, label: "Email du nouveau colocataire" %>
        <%= f.button :submit, "Ajouter colocataire", class: "btn-addcoloc" %>
      <% end %>
    </div>
  </div>



  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
        <%= simple_form_for(@colocation) do |f| %>
          <%= f.input :photo, as: :file %>
          <%= f.button :submit, "Ajouter une photo" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>